# -*- coding: utf-8 -*-
"""Deep learning assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XLajADW9PfXZQOLO_I-vklHF3YEvFkKJ
"""

#IMPORTING NECESSARY LIBRARIES
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import time
from datetime import datetime
import pytz  # Ensure you have pytz installed for timezone handling
import dateutil.parser  # Import the dateutil module

#GET THE CHAT ID IN THE COMMENTS SECTION
def get_live_chat_id(api_key, video_id):
  """Fetches the live chat ID for a live video using the YouTube API."""
  youtube = build("youtube", "v3", developerKey=api_key)
  request = youtube.videos().list(
      part="liveStreamingDetails",
      id=video_id
  )
  response = request.execute()
  live_chat_id = response['items'][0]['liveStreamingDetails']['activeLiveChatId']
  return live_chat_id

#GET THE COMMENTS FROM CHAT ID
def get_live_chat_messages(api_key, live_chat_id, max_results=5, pageToken=None):
  """Fetch live chat messages from a live chat."""
  youtube = build("youtube", "v3", developerKey=api_key)
  request = youtube.liveChatMessages().list(
      liveChatId=live_chat_id,
      part="snippet,authorDetails",
      maxResults=max_results,
      pageToken=pageToken
  )
  response = request.execute()
  return response

# PERFORMING SENTIMENT ANALYSIS
from textblob import TextBlob

def analyze_sentiment(message):
    """Analyze sentiment of the given message and return classification."""
    analysis = TextBlob(message)  # Creates a TextBlob object for sentiment analysis.
    polarity = analysis.sentiment.polarity  # Retrieves the polarity score of the message.

    if polarity > 0:
        return "positive"  # Returns "positive" if the polarity is greater than 0.
    elif polarity < 0:
        return "negative"  # Returns "negative" if the polarity is less than 0.
    else:
        return "neutral"  # Returns "neutral" if the polarity is 0.

#CONVERTING THE YOUTUBE TIME INTO HUMAN READABLE FORMAT
def format_timestamp(timestamp):
  """Converts ISO 8601 timestamp to a human-readable format."""
  dt = dateutil.parser.parse(timestamp)
  return dt.strftime("%Y-%m-%d %H:%M:%S %Z")

def get_current_time():
  """Returns the current time in a human-readable format."""
  tz = pytz.timezone('Asia/Kolkata')  # Use India Standard Time
  now = datetime.now(tz)
  return now.strftime("%Y-%m-%d %H:%M:%S %Z")

#FETCH THE LAST 5 COMMENTS OF THE CURRENT TIME
def fetch_last_5_comments(api_key, video_id, fetch_interval=5, max_duration=60):
  """Fetch and display the last 5 live comments regardless of the start time."""
  backoff_factor = 2  # Factor to increase wait time between retries
  wait_time = 2  # Initial wait time in seconds

  # Initialize start_time and end_time
  start_time = time.time()
  end_time = time.time() + max_duration

  for _ in range(5):  # Retry up to 5 times
    live_chat_id = get_live_chat_id(api_key, video_id)  # Get the live chat ID for the video

    try:
      response = get_live_chat_messages(api_key, live_chat_id)  # Fetch live chat messages

      # **Modification:** Get only the most recent messages (up to 5)
      comments = response.get('items', [])[:5]  # Get first 5 items (comments) or empty list

      # Display the comments and their sentiment (if comments exist)
      if comments:
        for item in comments:
          author = item['authorDetails']['displayName']
          message = item['snippet']['textMessageDetails']['messageText']
          timestamp = item['snippet']['publishedAt']
          formatted_timestamp = format_timestamp(timestamp)
          sentiment = analyze_sentiment(message)

          # Print current time and comment details
          print(f"Current Time: {get_current_time()}")
          print(f"Author: {author}")
          print(f"Message: {message}")
          print(f"Sentiment: {sentiment}")
          print(f"Timestamp: {formatted_timestamp}")
          print()  # Add a blank line between messages
      else:
        print("No comments found.")

      # No need to check for next page token as we only care about most recent messages

      # Check if the maximum duration has been exceeded
      if time.time() > end_time:
        print("Maximum duration exceeded.")
        break

      time.sleep(fetch_interval)  # Wait before fetching the next batch of messages
      break  # Exit loop on successful execution
    except HttpError as e:
      # If quota is exceeded, retry with exponential backoff
      if 'quotaExceeded' in str(e):
        print(f"Quota exceeded, retrying in {wait_time} seconds...")
        time.sleep(wait_time)
        wait_time *= backoff_factor
      else:
        # Re-raise other HTTP errors
        raise e
    else:
      # Notify if all retries fail
      print("Failed to fetch comments after all retries.")

# API AND VIDEO ID
api_key = "AIzaSyC-T6qGelPPdbeXGC62p2of076WGhosJbw"  #  actual API key
video_id = "sFCnoyKXebU"  # live video ID

fetch_last_5_comments(api_key, video_id)